import { derived, estimated, measured } from '../core/param';
import type { SpeciesDef } from './types';

export const atta: SpeciesDef = {
  id: 'atta',
  name: 'Atta cephalotes',
  common: 'Leaf-cutter ant',
  subfamily: 'Myrmicinae',
  blurb:
    'A fungus farmer with the most extreme worker polymorphism of any ant. Medium workers cut leaf fragments sized to their own bodies and carry them along cleared trunk trails; minims tend the fungus garden and ride on fragments to fend off parasitic flies; majors defend. Leaves feed the fungus, and the fungus feeds the colony.',
  highlights: [
    'Extreme polymorphism (head width 0.7 to >3 mm) with size-based division of labour (Wilson 1980)',
    'Fragment size scales with cutter size; speed falls linearly with load (Burd 1996)',
    'Persistent, physically cleared trunk trails + potent poison-gland trail pheromone',
    'Minims hitchhike on leaf fragments (Feener & Moss 1990)',
    'Fungus garden converts leaves into food; refuse kept in underground chambers',
    'Forages day and night',
  ],
  habitat: {
    label: 'Lowland tropical forest edge',
    ground: 'rainforest',
    surfaceMin: estimated(23, '°C', 'Tropical forest floor.'),
    surfaceMax: estimated(31, '°C', ''),
    airMin: estimated(23, '°C', ''),
    airMax: estimated(30, '°C', ''),
    sunrise: measured(6, 'h', [], 'Equatorial.'),
    sunset: measured(18.2, 'h', [], ''),
    soilDiffusivity: estimated(0.4, 'mm²/s', 'Clay-rich tropical soil.'),
    startHour: 17,
    indoor: false,
  },
  arena: {
    width: estimated(5000, 'mm', 'Trunk trails commonly extend tens of metres; arena truncated.'),
    height: estimated(4000, 'mm', ''),
    cell: estimated(6, 'mm', 'Trunk trails are several cm wide.'),
    relief: estimated(60, 'mm', ''),
  },
  morphology: {
    lengthMin: derived(2.0, 'mm', 'wilson1980', 'Minims (HW ≈0.7 mm).'),
    lengthMax: derived(14, 'mm', 'wilson1980', 'Majors/soldiers.'),
    sizeDistribution: 'atta',
    massCoef: estimated(0.014, 'mg/mm³', 'Gives ≈5 mg for a 7 mm media.'),
    headAllometry: estimated(0.45, '', 'Strong positive allometry of head width.'),
    legRatio: estimated(1.0, '', 'Long legs.'),
    rideHeight: estimated(0.22, '', ''),
    petioleNodes: 2,
    cocoons: false,
    antennalClub: false,
    spines: true,
    colors: { head: '#8f3f1c', mesosoma: '#9d4a22', gaster: '#7b3517', legs: '#a5562a' },
  },
  locomotion: {
    v28: derived(43, 'mm/s', 'hurlbert2008', 'A. colombica: 43.1 mm/s for a 5 mg worker (mass-scaling table).'),
    refMass: measured(5, 'mg', 'hurlbert2008'),
    activationEnergy: derived(0.75, 'eV', 'hurlbert2008', 'A. colombica studies: 0.6 and 0.93 eV.'),
    massExponent: measured(0.34, '', 'hurlbert2008', 'A. colombica mass exponent.'),
    tempMin: estimated(14, '°C', ''),
    tempOpt: estimated(33, '°C', ''),
    tempMax: estimated(42, '°C', ''),
    turnNoise: estimated(0.9, 'rad/√s', ''),
    loadSlope: derived(0.12, '1/body-mass', ['burd1996', 'attaLoad'], 'Speed declines linearly with load mass.'),
  },
  senses: {
    antennaRatio: estimated(0.5, '', ''),
    antennaAngle: estimated(0.55, 'rad', ''),
    trailGain: estimated(7, 'rad/s', ''),
    foodDetect: estimated(60, 'mm', 'Plants detected by odour at short range.'),
    nestDetect: estimated(60, 'mm', ''),
  },
  navigation: {
    compassBias: estimated(0.1, 'rad', ''),
    compassNoise: estimated(0.03, 'rad', ''),
    odometerError: estimated(0.1, '', ''),
    visualCatchment: estimated(150, 'mm', ''),
    systematicSearch: false,
    siteFidelity: estimated(0.85, '', 'Foragers return repeatedly to the same plant.'),
    memoryFailures: estimated(2, 'visits', ''),
  },
  foraging: {
    mode: 'leafcutter',
    foods: ['leaf', 'sugar'],
    bodyTempMin: estimated(18, '°C', ''),
    bodyTempMax: estimated(36, '°C', ''),
    diurnal: false,
    cropVolume: estimated(0.4, 'µL', ''),
    drinkRate: estimated(0.004, 'µL/s', ''),
    carryCapacity: measured(7.8, '× body mass', 'attaLoad', 'Maximum; chosen loads are lower.'),
    giveUpTime: estimated(1800, 's', ''),
    exploreRadius: estimated(1200, 'mm', ''),
    restTime: estimated(300, 's', ''),
    scoutRate: estimated(0.5, '/h', ''),
    extranidalHazard: estimated(1 / (60 * 3600), '1/s', ''),
    recruitProbability: estimated(0.7, '', ''),
    recruitContacts: estimated(5, 'ants', ''),
    recruitResponse: estimated(0.35, '', ''),
  },
  pheromones: [
    {
      id: 'trail',
      label: 'Recruitment trail (MMPC)',
      gland: 'poison gland',
      lifetime: estimated(2 * 3600, 's', 'Methyl 4-methylpyrrole-2-carboxylate is extremely potent; recruitment trails persist for hours.'),
      deposit: estimated(1, 'units/mm', ''),
      threshold: estimated(0.4, 'units/mm', ''),
      weight: estimated(1, '', ''),
      laidBy: 'recruiters',
    },
    {
      id: 'cleared',
      label: 'Cleared trunk trail',
      gland: '(physical clearing + orientation cues)',
      lifetime: estimated(14 * 86400, 's', 'Cleared trails persist for weeks without traffic.'),
      deposit: estimated(0.004, 'units/mm', 'Accumulates with traffic.'),
      threshold: estimated(1, 'units/mm', ''),
      weight: estimated(0.5, '', 'Guides ants; also raises walking speed.'),
      laidBy: 'traffic',
    },
  ],
  alarm: {
    radius: estimated(60, 'mm', '4-methyl-3-heptanone alarm.', 'bossert1963'),
    fade: estimated(30, 's', '', 'bossert1963'),
    aggression: estimated(0.7, '', 'Majors respond strongly.'),
  },
  colony: {
    queens: measured(1, '', 'holldobler1990'),
    workers: estimated(3000, 'workers', 'Scaled-down young colony; mature colonies hold millions.'),
    eggs: estimated(300, '', ''),
    larvae: estimated(300, '', ''),
    pupae: estimated(200, '', ''),
    eggsPerQueenDay: estimated(300, 'eggs/day', 'Young colony; mature queens lay >20 000/day.'),
    workerLifespan: estimated(120, 'days', ''),
    forageAge: estimated(25, 'days', 'Size matters more than age in Atta.'),
    inactiveFraction: estimated(0.3, '', ''),
    volumePerWorker: estimated(1200, 'mm³', 'Includes fungus garden chambers.'),
    workerCap: 6000,
  },
  development: {
    egg: estimated(22, 'd', 'Atta worker development ~50–60 d total.'),
    larva: estimated(24, 'd', ''),
    pupa: estimated(12, 'd', ''),
    refTemp: estimated(25, '°C', ''),
    lowerThreshold: estimated(15, '°C', ''),
    upperThreshold: estimated(31, '°C', 'Fungus garden suffers above ~30 °C.'),
    broodTempPref: estimated(25, '°C', 'Brood lives in the garden, kept at 24–26 °C.'),
  },
  nest: {
    architecture: 'atta',
    voxel: estimated(8, 'mm', ''),
    depth: estimated(1200, 'mm', 'Mature nests reach 6 m; young colony.'),
    radius: estimated(500, 'mm', ''),
    tunnelWidth: estimated(16, 'mm', ''),
    chamberHeight: estimated(120, 'mm', 'Garden chambers are roughly spherical.'),
    moundHeight: estimated(80, 'mm', 'Loose excavated soil mound.'),
    moundRadius: estimated(400, 'mm', ''),
    pelletTime: estimated(60, 's', ''),
    pelletVolume: estimated(10, 'mm³', ''),
    queenDepth: estimated(0.5, '', ''),
  },
  physiology: {
    metabolicRate: derived(1.2, 'µg/h/mg^0.75', 'gillooly2001', ''),
    activeFactor: estimated(3, '×', ''),
    reserveDays: estimated(10, 'd', ''),
    larvalProtein: estimated(0.6, 'mg/mg', 'Supplied as fungal gongylidia.'),
    eggCost: estimated(0.02, 'mg', ''),
  },
  special: {
    leafcutter: {
      fragmentAreaCoef: estimated(1.2, 'mm²/mm²', 'Fragment area ≈1.2·L²: ~60 mm² for a 7 mm media (2–3× body mass).', 'wilson1980'),
      leafDensity: estimated(0.2, 'mg/mm²', 'Fresh leaf mass per area ≈ 200 g/m².'),
      cutRate: estimated(0.4, 'mm/s', 'Mandible cutting speed with stridulatory vibration (Roces & Hölldobler 1996).', 'roces1996'),
      hitchhikerProbability: derived(0.08, '', 'feener1990', 'Fraction of fragments with a minim rider by day.'),
      gardenPerWorker: estimated(4, 'mg', 'Fungus garden mass per worker.'),
      gardenYield: estimated(0.04, '1/day', 'Food (gongylidia) produced per mg garden per day.'),
      leafToGarden: estimated(0.4, 'mg/mg', 'Garden mass produced per mg of leaf.'),
      sapRate: estimated(0.001, 'µL/s', 'Plant sap imbibed while cutting.'),
    },
  },
  world: { aphidColonies: 0, sugarDrops: 0, insects: 0, insectRainPerHour: 0, seeds: 0, plants: 9, stones: 6, grit: 0 },
};
