import { derived, estimated, measured } from '../core/param';
import type { SpeciesDef } from './types';

export const cataglyphis: SpeciesDef = {
  id: 'cataglyphis',
  name: 'Cataglyphis fortis',
  common: 'Saharan desert ant',
  subfamily: 'Formicinae',
  blurb:
    'A solitary forager of featureless salt pans and a navigation virtuoso. Without pheromone trails, each ant integrates its path with a polarised-light sky compass and a stride-counting odometer, runs straight home with its prey, and performs an expanding-loop systematic search if the nest is not where its path integrator says it should be.',
  highlights: [
    'No recruitment pheromones: purely individual foraging',
    'Path integration (sky compass + stride odometer) with realistic error',
    'Systematic search: expanding centred loops around the fictive nest (Wehner & Srinivasan 1981)',
    'Forages at midday heat; long legs keep the body in cooler air; CTmax ≈ 53 °C',
    'Detects food odours over long distances (Buehlmann et al. 2014)',
    'Very fast: up to 0.62 m/s; forager life expectancy ≈ 6 days',
  ],
  habitat: {
    label: 'Tunisian salt pan, summer',
    ground: 'saltpan',
    surfaceMin: estimated(20, '°C', 'Night ground temperature in Saharan summer.'),
    surfaceMax: estimated(62, '°C', 'Salt-pan surface reaches ~60 °C.', 'gehring1995'),
    airMin: estimated(22, '°C', ''),
    airMax: estimated(40, '°C', ''),
    sunrise: measured(5.6, 'h', [], 'Summer at 34° N.'),
    sunset: measured(19.6, 'h', [], ''),
    soilDiffusivity: estimated(0.6, 'mm²/s', 'Dry sandy/salty crust.'),
    startHour: 8,
    indoor: false,
  },
  arena: {
    width: estimated(30000, 'mm', 'Forays exceed 100 m in total path length; arena 30 m.', 'wittlinger2007'),
    height: estimated(30000, 'mm', ''),
    cell: estimated(50, 'mm', 'No trail pheromone; grid only for terrain.'),
    relief: estimated(20, 'mm', 'Flat salt pan.'),
  },
  morphology: {
    lengthMin: estimated(5, 'mm', 'Moderately polymorphic, long-legged.'),
    lengthMax: estimated(10, 'mm', ''),
    sizeDistribution: 'continuous',
    massCoef: estimated(0.013, 'mg/mm³', 'Slender: ≈6.7 mg at 8 mm.'),
    headAllometry: estimated(0.05, '', ''),
    legRatio: estimated(1.35, '', 'Very long legs.'),
    rideHeight: estimated(0.5, '', 'Body held ~4 mm above the hot ground.'),
    petioleNodes: 1,
    cocoons: true,
    antennalClub: false,
    spines: false,
    colors: { head: '#18130f', mesosoma: '#1c1612', gaster: '#14100d', legs: '#2a221c' },
  },
  locomotion: {
    v28: derived(250, 'mm/s', ['hurlbert2008', 'pfeffer2019'], 'C. bicolor 137 mm/s at 28 °C while laden; C. fortis unladen up to 620 mm/s at high temperature.'),
    refMass: estimated(6, 'mg', ''),
    activationEnergy: measured(0.15, 'eV', 'hurlbert2008', 'C. bicolor: very shallow temperature dependence across 28–61 °C.'),
    massExponent: measured(0.25, '', 'hurlbert2008'),
    tempMin: estimated(15, '°C', ''),
    tempOpt: estimated(50, '°C', ''),
    tempMax: derived(53.5, '°C', 'gehring1995', 'CTmax of congeners 53.6–55.1 °C.'),
    turnNoise: estimated(0.6, 'rad/√s', 'Straight, fast runs.'),
    loadSlope: derived(0.12, '1/body-mass', 'burd1996', ''),
  },
  senses: {
    antennaRatio: estimated(0.45, '', ''),
    antennaAngle: estimated(0.5, 'rad', ''),
    trailGain: estimated(0, 'rad/s', 'No trail following.'),
    foodDetect: derived(400, 'mm', 'buehlmann2014', 'Food odours detected from metres downwind; reduced here (no wind model).'),
    nestDetect: estimated(150, 'mm', 'Nest odour plume (CO2) near the entrance.'),
  },
  navigation: {
    compassBias: estimated(0.03, 'rad', 'Precise sky compass.'),
    compassNoise: estimated(0.01, 'rad', ''),
    odometerError: derived(0.08, '', 'wittlinger2007', 'Stride integrator is the main error source; ~10% distance errors.'),
    visualCatchment: estimated(400, 'mm', 'Few landmarks on salt pans.'),
    systematicSearch: true,
    siteFidelity: estimated(0.8, '', 'Return to profitable feeders.'),
    memoryFailures: estimated(2, 'visits', ''),
  },
  foraging: {
    mode: 'solitary',
    foods: ['insect', 'seed'],
    bodyTempMin: estimated(28, '°C', 'Forages in the heat of the day.'),
    bodyTempMax: estimated(50, '°C', 'Retreats before CTmax.'),
    diurnal: true,
    cropVolume: estimated(0.3, 'µL', ''),
    drinkRate: estimated(0.006, 'µL/s', ''),
    carryCapacity: estimated(8, '× body mass', ''),
    giveUpTime: estimated(1500, 's', ''),
    exploreRadius: estimated(8000, 'mm', 'Foraging distances commonly 10–50 m.'),
    restTime: estimated(500, 's', ''),
    scoutRate: estimated(3, '/h', 'All foragers leave individually.'),
    extranidalHazard: derived(1 / (20 * 3600), '1/s', 'schmidHempel1984', 'Forager life expectancy ~6 d at a few hours outside per day.'),
    recruitProbability: estimated(0, '', 'No recruitment.'),
    recruitContacts: estimated(0, 'ants', ''),
    recruitResponse: estimated(0, '', ''),
  },
  pheromones: [],
  alarm: {
    radius: estimated(20, 'mm', ''),
    fade: estimated(10, 's', ''),
    aggression: estimated(0.2, '', 'Flee rather than fight.'),
  },
  colony: {
    queens: measured(1, '', 'holldobler1990', 'Monogynous.'),
    workers: estimated(500, 'workers', 'C. fortis colonies number hundreds to ~1000.'),
    eggs: estimated(50, '', ''),
    larvae: estimated(50, '', ''),
    pupae: estimated(40, '', ''),
    eggsPerQueenDay: estimated(15, 'eggs/day', ''),
    workerLifespan: estimated(120, 'days', 'Long in-nest phase, very short forager phase.'),
    forageAge: estimated(28, 'days', ''),
    inactiveFraction: estimated(0.4, '', ''),
    volumePerWorker: estimated(60, 'mm³', ''),
    workerCap: 3000,
  },
  development: {
    egg: estimated(8, 'd', ''),
    larva: estimated(12, 'd', ''),
    pupa: estimated(13, 'd', ''),
    refTemp: estimated(30, '°C', ''),
    lowerThreshold: estimated(16, '°C', ''),
    upperThreshold: estimated(36, '°C', ''),
    broodTempPref: estimated(31, '°C', ''),
  },
  nest: {
    architecture: 'cataglyphis',
    voxel: estimated(4, 'mm', ''),
    depth: estimated(500, 'mm', ''),
    radius: estimated(120, 'mm', ''),
    tunnelWidth: estimated(8, 'mm', ''),
    chamberHeight: estimated(12, 'mm', ''),
    moundHeight: estimated(0, 'mm', 'Simple hole.'),
    moundRadius: estimated(40, 'mm', ''),
    pelletTime: estimated(40, 's', ''),
    pelletVolume: estimated(3, 'mm³', ''),
    queenDepth: estimated(0.7, '', ''),
  },
  physiology: {
    metabolicRate: derived(1.2, 'µg/h/mg^0.75', 'gillooly2001', ''),
    activeFactor: estimated(4, '×', 'Fast running.'),
    reserveDays: estimated(14, 'd', ''),
    larvalProtein: estimated(0.6, 'mg/mg', ''),
    eggCost: estimated(0.08, 'mg', ''),
  },
  special: {},
  world: { aphidColonies: 0, sugarDrops: 0, insects: 15, insectRainPerHour: 12, seeds: 0, plants: 6, stones: 10, grit: 0 },
};
