import { derived, estimated, measured } from '../core/param';
import type { SpeciesDef } from './types';

export const formica: SpeciesDef = {
  id: 'formica',
  name: 'Formica rufa',
  common: 'Red wood ant',
  subfamily: 'Formicinae',
  blurb:
    'A large, visually guided forest ant that builds sun-warmed thatch mounds and harvests honeydew from aphids on trees along permanent trunk trails. Experienced foragers keep returning to the same tree along personal, visually memorised routes (Ortstreue) while naive ants use the odour trails as scaffolding.',
  highlights: [
    'Thatch mound warmed by sun and metabolism above a soil nest',
    'Site fidelity (Ortstreue): individual, long-term visual route memory',
    'Odour trunk trails used mainly by naive foragers',
    'Honeydew harvesting from aphid colonies; also hunts insects',
    'Polygynous; diurnal foraging',
    'Formic acid spraying as alarm/defence',
  ],
  habitat: {
    label: 'Temperate conifer forest clearing, summer',
    ground: 'forest',
    surfaceMin: estimated(10, '°C', 'Forest floor at night in summer.'),
    surfaceMax: estimated(30, '°C', 'Partly sunny forest clearing.'),
    airMin: estimated(10, '°C', ''),
    airMax: estimated(24, '°C', ''),
    sunrise: measured(4.8, 'h', [], 'Summer at 55° N.'),
    sunset: measured(21.5, 'h', [], ''),
    soilDiffusivity: estimated(0.35, 'mm²/s', 'Organic forest soil.'),
    startHour: 8,
    indoor: false,
  },
  arena: {
    width: estimated(4000, 'mm', 'Aphid trees may be up to 100 m away; arena truncated.', 'woodantRoutes2023'),
    height: estimated(3000, 'mm', ''),
    cell: estimated(5, 'mm', ''),
    relief: estimated(80, 'mm', ''),
  },
  morphology: {
    lengthMin: measured(4.5, 'mm', 'holldobler1990'),
    lengthMax: measured(9, 'mm', 'holldobler1990'),
    sizeDistribution: 'continuous',
    massCoef: estimated(0.02, 'mg/mm³', 'Robust body: ≈5.5 mg for a 6.5 mm worker (Hurlbert data 4.9–12.9 mg).', 'hurlbert2008'),
    headAllometry: estimated(0.1, '', ''),
    legRatio: estimated(0.95, '', ''),
    rideHeight: estimated(0.22, '', ''),
    petioleNodes: 1,
    cocoons: true,
    antennalClub: false,
    spines: false,
    colors: { head: '#7f2f1a', mesosoma: '#a23c1f', gaster: '#1b1411', legs: '#3c2a22' },
  },
  locomotion: {
    v28: measured(50.6, 'mm/s', 'hurlbert2008', 'F. rufa (Holt 1955 data), extrapolated to 28 °C from 8–21 °C measurements.'),
    refMass: estimated(5.5, 'mg', ''),
    activationEnergy: measured(0.55, 'eV', 'hurlbert2008'),
    massExponent: measured(0.26, '', 'hurlbert2008', 'F. rufa mass exponent (n.s.).'),
    tempMin: estimated(4, '°C', 'Measured down to 8 °C.', 'hurlbert2008'),
    tempOpt: estimated(30, '°C', ''),
    tempMax: estimated(44, '°C', ''),
    turnNoise: estimated(0.8, 'rad/√s', ''),
    loadSlope: derived(0.12, '1/body-mass', 'burd1996', ''),
  },
  senses: {
    antennaRatio: estimated(0.5, '', ''),
    antennaAngle: estimated(0.55, 'rad', ''),
    trailGain: estimated(4, 'rad/s', 'Odour trails less dominant than in Lasius.'),
    foodDetect: estimated(30, 'mm', ''),
    nestDetect: estimated(80, 'mm', ''),
  },
  navigation: {
    compassBias: estimated(0.06, 'rad', ''),
    compassNoise: estimated(0.02, 'rad', ''),
    odometerError: estimated(0.08, '', ''),
    visualCatchment: estimated(500, 'mm', 'Strong landmark use in cluttered woodland.', 'rosengren1986'),
    systematicSearch: false,
    siteFidelity: measured(0.95, '', ['rosengren1986', 'woodantRoutes2023'], 'Ortstreue: foragers keep returning to the same tree.'),
    memoryFailures: estimated(4, 'visits', 'Long-term memory persists even over winter.', 'rosengren1986'),
  },
  foraging: {
    mode: 'trunk',
    foods: ['honeydew', 'insect', 'sugar'],
    bodyTempMin: estimated(10, '°C', ''),
    bodyTempMax: estimated(36, '°C', ''),
    diurnal: true,
    cropVolume: estimated(1.5, 'µL', 'Large crop; ≈1–2 mg honeydew loads.'),
    drinkRate: estimated(0.02, 'µL/s', ''),
    carryCapacity: estimated(5, '× body mass', ''),
    giveUpTime: estimated(1800, 's', ''),
    exploreRadius: estimated(900, 'mm', ''),
    restTime: estimated(400, 's', ''),
    scoutRate: estimated(0.4, '/h', ''),
    extranidalHazard: estimated(1 / (60 * 3600), '1/s', ''),
    recruitProbability: estimated(0.5, '', ''),
    recruitContacts: estimated(4, 'ants', ''),
    recruitResponse: estimated(0.3, '', ''),
  },
  pheromones: [
    {
      id: 'trail',
      label: 'Hindgut trail',
      gland: 'hindgut',
      lifetime: estimated(3600, 's', 'Formica odour trails persist for tens of minutes to hours.'),
      deposit: estimated(1, 'units/mm', ''),
      threshold: estimated(0.6, 'units/mm', ''),
      weight: estimated(0.7, '', 'Experienced ants weight private (visual) information more.', 'woodantRoutes2023'),
      laidBy: 'recruiters',
    },
  ],
  alarm: {
    radius: estimated(80, 'mm', 'Formic acid + undecane; larger workers, larger active space.', 'bossert1963'),
    fade: estimated(25, 's', ''),
    aggression: estimated(0.8, '', 'Spray formic acid.'),
  },
  colony: {
    queens: estimated(5, '', 'Often polygynous.'),
    workers: estimated(2500, 'workers', 'Scaled; mature mounds hold 100 000+.'),
    eggs: estimated(250, '', ''),
    larvae: estimated(250, '', ''),
    pupae: estimated(200, '', ''),
    eggsPerQueenDay: estimated(30, 'eggs/day', ''),
    workerLifespan: estimated(300, 'days', 'Workers live up to ~1–2 years.'),
    forageAge: estimated(40, 'days', ''),
    inactiveFraction: estimated(0.35, '', ''),
    volumePerWorker: estimated(60, 'mm³', 'Includes mound galleries.'),
    workerCap: 6000,
  },
  development: {
    egg: estimated(14, 'd', ''),
    larva: estimated(12, 'd', ''),
    pupa: estimated(14, 'd', ''),
    refTemp: estimated(25, '°C', ''),
    lowerThreshold: estimated(12, '°C', ''),
    upperThreshold: estimated(32, '°C', ''),
    broodTempPref: derived(27, '°C', 'frouz2000', 'Mound cores are kept at ~25–30 °C in summer.'),
  },
  nest: {
    architecture: 'formica',
    voxel: estimated(5, 'mm', ''),
    depth: estimated(450, 'mm', ''),
    radius: estimated(350, 'mm', ''),
    tunnelWidth: estimated(10, 'mm', ''),
    chamberHeight: estimated(15, 'mm', ''),
    moundHeight: estimated(300, 'mm', 'Thatch dome of conifer needles (scaled).'),
    moundRadius: estimated(350, 'mm', ''),
    pelletTime: estimated(40, 's', ''),
    pelletVolume: estimated(4, 'mm³', ''),
    queenDepth: estimated(0.2, '', 'Queens and brood stay in the warm upper mound/ground level.'),
  },
  physiology: {
    metabolicRate: derived(1.2, 'µg/h/mg^0.75', 'gillooly2001', ''),
    activeFactor: estimated(3, '×', ''),
    reserveDays: estimated(20, 'd', ''),
    larvalProtein: estimated(0.6, 'mg/mg', ''),
    eggCost: estimated(0.06, 'mg', ''),
  },
  special: { trunk: { routeMemoryWeight: estimated(1.5, '', 'Private visual route information outweighs odour trails in experienced ants.', 'woodantRoutes2023') } },
  world: { aphidColonies: 4, sugarDrops: 0, insects: 3, insectRainPerHour: 6, seeds: 0, plants: 5, stones: 8, grit: 0 },
};
