import { derived, estimated, measured } from '../core/param';
import type { SpeciesDef } from './types';

export const lasius: SpeciesDef = {
  id: 'lasius',
  name: 'Lasius niger',
  common: 'Black garden ant',
  subfamily: 'Formicinae',
  blurb:
    'The common European garden ant and the model organism of trail-pheromone research. Monomorphic workers tend aphids for honeydew and mass-recruit nestmates to food with hindgut trail pheromone, modulating how much they lay by food quality, distance and colony hunger.',
  highlights: [
    'Mass recruitment with hindgut trail pheromone (mean lifetime ≈ 47 min)',
    'Trail laying modulated by food quality, colony starvation, and distance (up to 22× more near the food)',
    'Combines trails with visual route memory',
    'Aphid tending for honeydew; scavenges insects',
    'Soil nest; volume regulated to group size (Rasse & Deneubourg)',
    'Cocooned pupae (Formicinae)',
  ],
  habitat: {
    label: 'Temperate lawn / garden, early summer',
    ground: 'garden',
    surfaceMin: estimated(12, '°C', 'Typical clear-sky early-summer minimum for a central European lawn.'),
    surfaceMax: estimated(34, '°C', 'Bare-soil surface maximum on a sunny early-summer day in central Europe.'),
    airMin: estimated(11, '°C', 'Central European June night.'),
    airMax: estimated(25, '°C', 'Central European June afternoon.'),
    sunrise: measured(5.0, 'h', [], 'Approximate sunrise at 50° N in June (local solar time).'),
    sunset: measured(21.0, 'h', [], 'Approximate sunset at 50° N in June (local solar time).'),
    soilDiffusivity: estimated(0.45, 'mm²/s', 'Typical moist loam thermal diffusivity (0.3–0.6 mm²/s).'),
    startHour: 8,
    indoor: false,
  },
  arena: {
    width: estimated(1200, 'mm', 'A garden patch large enough for typical L. niger foraging (most trails < 1 m).'),
    height: estimated(900, 'mm', 'See width.'),
    cell: estimated(2, 'mm', 'About half a body length so trails are resolved at antenna scale.'),
    relief: estimated(15, 'mm', 'Gentle unevenness of a lawn.'),
  },
  morphology: {
    lengthMin: derived(3.6, 'mm', 'khuong2016', 'Khuong et al. report 4.1 ± 0.14 mm; range set to ±3.5 SD with natural size variation.'),
    lengthMax: derived(4.8, 'mm', 'khuong2016', 'See lengthMin.'),
    sizeDistribution: 'mono',
    massCoef: estimated(0.012, 'mg/mm³', 'Gives ≈0.8 mg fresh mass for a 4.1 mm worker.'),
    headAllometry: estimated(0, '', 'Monomorphic: isometric head.'),
    legRatio: estimated(0.85, '', 'Hind leg length relative to body length for Lasius.'),
    rideHeight: estimated(0.22, '', 'Body carried about 1 mm above ground.'),
    petioleNodes: 1,
    cocoons: true,
    antennalClub: false,
    spines: false,
    colors: { head: '#2b2420', mesosoma: '#3a2e27', gaster: '#1e1915', legs: '#4a3a30' },
  },
  locomotion: {
    v28: derived(20, 'mm/s', 'hurlbert2008', 'No L. niger entry in Hurlbert Table 2; similar-sized Linepithema humile runs 30.9 mm/s at 28 °C. Lasius trail speeds are lower (~15–25 mm/s).'),
    refMass: estimated(0.8, 'mg', 'Mass of a 4.1 mm worker (see massCoef).'),
    activationEnergy: derived(0.47, 'eV', 'hurlbert2008', 'Mean activation energy across 22 ant species (Hurlbert et al. 2008).'),
    massExponent: measured(0.25, '', 'hurlbert2008', 'Central tendency of the mass–speed exponent.'),
    tempMin: estimated(5, '°C', 'Temperate Lasius remain mobile near 5 °C; activity lower limit 10–12 °C.'),
    tempOpt: estimated(34, '°C', 'Speed plateaus above ~34 °C in temperate ants.'),
    tempMax: estimated(45, '°C', 'Typical CTmax of temperate Formicinae (42–47 °C).'),
    turnNoise: estimated(1.1, 'rad/√s', 'Produces sinuosity of exploring Lasius scouts comparable to field tracks.'),
    loadSlope: derived(0.12, '1/body-mass', 'burd1996', 'Linear speed decline with load as measured in leaf-cutters; assumed similar.'),
  },
  senses: {
    antennaRatio: estimated(0.55, '', 'Antennal reach in front of head relative to body length.'),
    antennaAngle: estimated(0.6, 'rad', 'Antennae held ~35° from the body axis while trail following.'),
    trailGain: estimated(5, 'rad/s', 'Tuned so ants stay on a single-passage trail over ~20 cm as in Beckers et al. 1992.', 'beckers1992'),
    foodDetect: estimated(15, 'mm', 'Short-range olfactory detection of sugar/insects.'),
    nestDetect: estimated(25, 'mm', 'Nest odour / CO2 plume detection.'),
  },
  navigation: {
    compassBias: estimated(0.1, 'rad', 'Per-trip systematic heading error; Lasius uses PI with visual route memory (Evison et al. 2008).', 'evison2008'),
    compassNoise: estimated(0.03, 'rad', 'Per-step heading reading error.'),
    odometerError: estimated(0.1, '', 'Fractional distance error per trip.'),
    visualCatchment: estimated(80, 'mm', 'Familiar visual surroundings near the nest allow direct homing.', 'evison2008'),
    systematicSearch: false,
    siteFidelity: estimated(0.6, '', 'Experienced Lasius foragers return to rewarded sites (private information).', 'evison2008'),
    memoryFailures: estimated(2, 'visits', 'Unrewarded visits before switching back to social information.'),
  },
  foraging: {
    mode: 'mass',
    foods: ['sugar', 'honeydew', 'insect'],
    bodyTempMin: estimated(10, '°C', 'Lower limit of activity 10–12 °C (historical literature).'),
    bodyTempMax: estimated(38, '°C', 'Foraging declines strongly above ~38 °C body temperature.'),
    diurnal: false,
    cropVolume: estimated(0.4, 'µL', 'Typical full crop load of L. niger foragers (≈0.3–0.5 µL).', 'mailleux2000'),
    drinkRate: estimated(0.006, 'µL/s', 'Gives ~1 min feeding bouts at 1 M sucrose.', 'mailleux2000'),
    carryCapacity: estimated(5, '× body mass', 'Single-worker transport limit; heavier items need cooperation or cutting.'),
    giveUpTime: estimated(900, 's', 'Unsuccessful scouts typically return within 10–20 min.'),
    exploreRadius: estimated(300, 'mm', 'Typical excursion radius of scouts.'),
    restTime: estimated(240, 's', 'Time spent in nest between trips.'),
    scoutRate: estimated(0.5, '/h', 'Spontaneous exploration rate of available foragers.'),
    extranidalHazard: estimated(1 / (40 * 3600), '1/s', 'Gives ~40 h of foraging time to death by predation/accident.'),
    recruitProbability: estimated(0.8, '', 'Probability that a successful forager lays trail and recruits (modulated by quality and hunger).', 'beckers1993'),
    recruitContacts: estimated(4, 'ants', 'Nestmates stimulated per recruitment event.'),
    recruitResponse: estimated(0.35, '', 'Probability a contacted available forager leaves to follow the trail.'),
  },
  pheromones: [
    {
      id: 'trail',
      label: 'Trail pheromone',
      gland: 'hindgut',
      lifetime: measured(47 * 60, 's', ['lasiusLifetimeModel', 'beckers1992'], 'Mean lifetime of the L. niger trail.'),
      deposit: estimated(1, 'units/mm', 'Normalisation: one fresh passage = 1 unit.'),
      threshold: estimated(0.6, 'units/mm', 'A single fresh passage is followed by most recruits.'),
      weight: estimated(1, '', 'Attractive.'),
      laidBy: 'recruiters',
    },
  ],
  alarm: {
    radius: estimated(30, 'mm', 'Formicine alarm (formic acid/undecane) active space for a small worker.', 'bossert1963'),
    fade: estimated(20, 's', 'Volatile alarm components.', 'bossert1963'),
    aggression: estimated(0.4, '', 'Moderately defensive.'),
  },
  colony: {
    queens: measured(1, '', 'holldobler1990', 'Monogynous.'),
    workers: estimated(500, 'workers', 'A young established colony (mature colonies reach ~10 000).'),
    eggs: estimated(80, '', 'Brood typical of early summer.'),
    larvae: estimated(70, '', ''),
    pupae: estimated(50, '', ''),
    eggsPerQueenDay: estimated(40, 'eggs/day', 'Laying rate for a colony of this size in summer; limited by protein supply.'),
    workerLifespan: estimated(180, 'days', 'Field worker longevity of several months to a year.'),
    forageAge: estimated(30, 'days', 'Age polyethism: workers start foraging after ~1 month.'),
    inactiveFraction: estimated(0.35, '', 'Proportion of workers inactive at any time in most ant colonies.'),
    volumePerWorker: estimated(30, 'mm³', 'Nest volume per worker; nest size proportional to worker number (Rasse & Deneubourg 2001).', 'rasse2001'),
    workerCap: 4000,
  },
  development: {
    egg: derived(12, 'd', 'antkeeping', 'Rearing records at 25 °C: 9–16 d.'),
    larva: derived(11, 'd', 'antkeeping', 'Rearing records at 25 °C: 9–13 d.'),
    pupa: derived(11, 'd', 'antkeeping', 'Rearing records at 25 °C: 9–12 d.'),
    refTemp: measured(25, '°C', 'antkeeping'),
    lowerThreshold: estimated(13, '°C', 'Typical lower developmental threshold for temperate ants.'),
    upperThreshold: estimated(32, '°C', 'Development rate declines above ~32 °C.'),
    broodTempPref: estimated(26, '°C', 'Nurses move brood towards ~24–28 °C.'),
  },
  nest: {
    architecture: 'lasius',
    voxel: estimated(2.5, 'mm', 'Tunnel width ≈ 1.5–2 body widths; voxel half a tunnel width.'),
    depth: estimated(350, 'mm', 'L. niger nests mostly within the top 30–50 cm.'),
    radius: estimated(150, 'mm', 'Lateral extent of the nest.'),
    tunnelWidth: estimated(5, 'mm', 'About 4 body widths.'),
    chamberHeight: estimated(7.5, 'mm', '~2 worker heights; cf. template height 4–8.5 mm in Khuong et al.', 'khuong2016'),
    moundHeight: estimated(20, 'mm', 'Small crater/mound of excavated soil.'),
    moundRadius: estimated(60, 'mm', ''),
    pelletTime: estimated(60, 's', 'Time to loosen one soil pellet.', 'rasse2001'),
    pelletVolume: estimated(1.0, 'mm³', 'Pellet carried in mandibles ≈ head-sized.'),
    queenDepth: estimated(0.6, '', 'Queen stays in the lower part of the nest.'),
  },
  physiology: {
    metabolicRate: derived(1.2, 'µg/h/mg^0.75', 'gillooly2001', 'Resting ant metabolism ≈1 µL O2/h/mg converted to sucrose equivalents.'),
    activeFactor: estimated(3, '×', 'Walking raises metabolic rate several-fold.'),
    reserveDays: estimated(14, 'd', 'Fed Lasius workers survive about two weeks without food.'),
    larvalProtein: estimated(0.6, 'mg/mg', 'Protein needed per mg of adult worker produced.'),
    eggCost: estimated(0.012, 'mg', 'Egg mass ≈ 1.5% of worker mass.'),
  },
  special: {},
  world: { aphidColonies: 3, sugarDrops: 1, insects: 3, insectRainPerHour: 2, seeds: 0, plants: 3, stones: 8, grit: 0 },
};
