import { derived, estimated, measured } from '../core/param';
import type { SpeciesDef } from './types';

export const monomorium: SpeciesDef = {
  id: 'monomorium',
  name: 'Monomorium pharaonis',
  common: "Pharaoh ant",
  subfamily: 'Myrmicinae',
  blurb:
    "A tiny, polygynous tramp ant of heated buildings. Colonies build trail networks using at least three pheromones: a long-lasting attractive trail that maps the network, a short-lived attractive trail to current food, and a repellent 'no entry' signal on unrewarding branches.",
  highlights: [
    'Three trail pheromones: long-lived (days), short-lived attractive (~33 min), repellent "no entry" (~78 min)',
    'Repellent effect initially ~2× the short attractant (48% vs 25%)',
    'Polygyny: many queens per nest',
    'Nests in pre-existing cavities (no excavation)',
    'Very small (≈2 mm) and slow; poor path integration, relies on trails',
    'Constant indoor climate',
  ],
  habitat: {
    label: 'Heated building (kitchen floor)',
    ground: 'kitchen',
    surfaceMin: estimated(25, '°C', 'Heated indoor environment.'),
    surfaceMax: estimated(27, '°C', 'Heated indoor environment.'),
    airMin: estimated(24.5, '°C', ''),
    airMax: estimated(26.5, '°C', ''),
    sunrise: estimated(7, 'h', 'Indoor light cycle.'),
    sunset: estimated(22, 'h', 'Indoor light cycle.'),
    soilDiffusivity: estimated(0.3, 'mm²/s', 'Wall/floor material; irrelevant at constant temperature.'),
    startHour: 9,
    indoor: true,
  },
  arena: {
    width: estimated(800, 'mm', 'Kitchen floor area.'),
    height: estimated(600, 'mm', ''),
    cell: estimated(1, 'mm', 'Half a body length.'),
    relief: estimated(0, 'mm', 'Flat floor.'),
  },
  morphology: {
    lengthMin: measured(2.0, 'mm', 'holldobler1990'),
    lengthMax: measured(2.4, 'mm', 'holldobler1990'),
    sizeDistribution: 'mono',
    massCoef: estimated(0.009, 'mg/mm³', 'Gives ≈0.1 mg per worker.'),
    headAllometry: estimated(0, '', ''),
    legRatio: estimated(0.8, '', ''),
    rideHeight: estimated(0.2, '', ''),
    petioleNodes: 2,
    cocoons: false,
    antennalClub: true,
    spines: false,
    colors: { head: '#c98d3a', mesosoma: '#d39a45', gaster: '#6b4019', legs: '#d6a35a' },
  },
  locomotion: {
    v28: estimated(10, 'mm/s', 'Scaled from Linepithema (30.9 mm/s at 28 °C) by mass^0.25 and the known slowness of Monomorium.', 'hurlbert2008'),
    refMass: estimated(0.1, 'mg', ''),
    activationEnergy: derived(0.47, 'eV', 'hurlbert2008', 'Mean across species.'),
    massExponent: measured(0.25, '', 'hurlbert2008'),
    tempMin: estimated(12, '°C', 'Tropical tramp species; sluggish below ~15 °C.'),
    tempOpt: estimated(32, '°C', ''),
    tempMax: estimated(42, '°C', ''),
    turnNoise: estimated(1.4, 'rad/√s', 'Tortuous exploration.'),
    loadSlope: derived(0.12, '1/body-mass', 'burd1996', 'Assumed as for leaf-cutters.'),
  },
  senses: {
    antennaRatio: estimated(0.5, '', ''),
    antennaAngle: estimated(0.6, 'rad', ''),
    trailGain: estimated(6, 'rad/s', ''),
    foodDetect: estimated(8, 'mm', ''),
    nestDetect: estimated(12, 'mm', ''),
  },
  navigation: {
    compassBias: estimated(0.35, 'rad', 'Tiny, poor-eyed ant: weak path integration; relies on trail geometry.', 'jackson2004'),
    compassNoise: estimated(0.08, 'rad', ''),
    odometerError: estimated(0.25, '', ''),
    visualCatchment: estimated(0, 'mm', 'No visual homing modelled.'),
    systematicSearch: false,
    siteFidelity: estimated(0.3, '', ''),
    memoryFailures: estimated(1, 'visits', ''),
  },
  foraging: {
    mode: 'mass',
    foods: ['sugar', 'insect'],
    bodyTempMin: estimated(18, '°C', ''),
    bodyTempMax: estimated(38, '°C', ''),
    diurnal: false,
    cropVolume: estimated(0.025, 'µL', 'Scaled from Lasius by body volume (≈1/8).'),
    drinkRate: estimated(0.0005, 'µL/s', 'Gives ~50 s feeding bouts.'),
    carryCapacity: estimated(4, '× body mass', ''),
    giveUpTime: estimated(900, 's', ''),
    exploreRadius: estimated(150, 'mm', ''),
    restTime: estimated(200, 's', ''),
    scoutRate: estimated(0.6, '/h', ''),
    extranidalHazard: estimated(1 / (100 * 3600), '1/s', 'Few predators indoors.'),
    recruitProbability: estimated(0.85, '', ''),
    recruitContacts: estimated(4, 'ants', ''),
    recruitResponse: estimated(0.35, '', ''),
  },
  pheromones: [
    {
      id: 'trailLong',
      label: 'Long-lived attractive trail',
      gland: 'unknown (persistent)',
      lifetime: derived(2 * 86400, 's', 'jackson2006', 'Trails remain detectable ≥ 48 h; mean lifetime set to 2 days.'),
      deposit: estimated(0.15, 'units/mm', 'Laid at low rate by all foragers, forming the network map.'),
      threshold: estimated(0.8, 'units/mm', 'Needs many passages to be followed.'),
      weight: estimated(0.6, '', 'Weaker guidance than the short-lived food trail.'),
      laidBy: 'all-foragers',
    },
    {
      id: 'trail',
      label: 'Short-lived attractive trail',
      gland: 'Dufour / poison gland',
      lifetime: derived(1000, 's', 'robinson2008', 'Behavioural effect lasts 33 min; mean lifetime chosen so effect falls below threshold ≈33 min after laying.'),
      deposit: estimated(1, 'units/mm', 'Normalisation.'),
      threshold: estimated(0.5, 'units/mm', ''),
      weight: measured(1, '', 'robinson2008', 'Reference effect (25% above control).'),
      laidBy: 'recruiters',
    },
    {
      id: 'repel',
      label: "Repellent 'no entry' signal",
      gland: 'unknown',
      lifetime: derived(2360, 's', 'robinson2008', 'Effect lasts 78 min (2.36× the attractant); lifetime scaled accordingly.'),
      deposit: estimated(1, 'units/mm', 'Deposited on unrewarding branches, concentrated near bifurcations.', 'robinson2005'),
      threshold: estimated(0.5, 'units/mm', ''),
      weight: derived(-1.9, '', 'robinson2008', 'Initial repellent effect 48% vs 25% attractive ⇒ ≈1.9× magnitude.'),
      laidBy: 'unrewarded',
    },
  ],
  alarm: {
    radius: estimated(15, 'mm', 'Weak alarm response in Monomorium.'),
    fade: estimated(15, 's', ''),
    aggression: estimated(0.1, '', 'Non-aggressive.'),
  },
  colony: {
    queens: estimated(8, '', 'Polygynous; dozens to hundreds of queens in large colonies.', 'peacock1950'),
    workers: estimated(800, 'workers', 'A budded nest; populations can be in the thousands.'),
    eggs: estimated(120, '', ''),
    larvae: estimated(150, '', ''),
    pupae: estimated(80, '', ''),
    eggsPerQueenDay: estimated(8, 'eggs/day', 'Per-queen laying rate; colony output scales with queen number.', 'peacock1950'),
    workerLifespan: derived(65, 'days', 'peacock1950', 'Workers live ~9–10 weeks.'),
    forageAge: estimated(20, 'days', ''),
    inactiveFraction: estimated(0.35, '', ''),
    volumePerWorker: estimated(3, 'mm³', 'Nests in small voids.'),
    workerCap: 4000,
  },
  development: {
    egg: derived(8, 'd', 'peacock1950', 'Total development ~38 d at 27 °C.'),
    larva: derived(19, 'd', 'peacock1950', ''),
    pupa: derived(11, 'd', 'peacock1950', ''),
    refTemp: measured(27, '°C', 'peacock1950'),
    lowerThreshold: estimated(18, '°C', 'Tropical species; brood development fails below ~18 °C.'),
    upperThreshold: estimated(33, '°C', ''),
    broodTempPref: estimated(28, '°C', ''),
  },
  nest: {
    architecture: 'cavity',
    voxel: estimated(1, 'mm', ''),
    depth: estimated(20, 'mm', 'Void under a skirting board.'),
    radius: estimated(60, 'mm', ''),
    tunnelWidth: estimated(2, 'mm', ''),
    chamberHeight: estimated(6, 'mm', ''),
    moundHeight: estimated(0, 'mm', ''),
    moundRadius: estimated(0, 'mm', ''),
    pelletTime: estimated(0, 's', 'No excavation.'),
    pelletVolume: estimated(0.1, 'mm³', ''),
    queenDepth: estimated(0.5, '', ''),
  },
  physiology: {
    metabolicRate: derived(1.2, 'µg/h/mg^0.75', 'gillooly2001', 'As Lasius.'),
    activeFactor: estimated(3, '×', ''),
    reserveDays: estimated(7, 'd', 'Small ants starve faster.'),
    larvalProtein: estimated(0.6, 'mg/mg', ''),
    eggCost: estimated(0.0015, 'mg', ''),
  },
  special: {},
  world: { aphidColonies: 0, sugarDrops: 2, insects: 2, insectRainPerHour: 0.5, seeds: 0, plants: 0, stones: 0, grit: 0 },
};
