import { derived, estimated, measured } from '../core/param';
import type { SpeciesDef } from './types';

export const pogonomyrmex: SpeciesDef = {
  id: 'pogonomyrmex',
  name: 'Pogonomyrmex barbatus',
  common: 'Red harvester ant',
  subfamily: 'Myrmicinae',
  blurb:
    "A seed harvester of desert grasslands whose colonies regulate foraging without any central control: foragers inside the nest leave at a rate set by how often successful foragers return. Each morning, patrollers scout first, and foraging begins only after they come back safely.",
  highlights: [
    'Interaction-rate regulation of forager exits (Prabhakar, Dektar & Gordon 2012 model)',
    'Morning patrollers gate the start of foraging (Greene & Gordon)',
    'Individual seed search; trip time dominated by search time',
    'Seeds stored in granaries; cleared nest disc and surface midden',
    'Alarm pheromone active space ≈6 cm, fading in ≈35 s (Bossert & Wilson 1963, P. badius)',
    'Shallow temperature dependence of speed (E ≈ 0.33 eV)',
  ],
  habitat: {
    label: 'Chihuahuan desert grassland, summer (SE Arizona / New Mexico)',
    ground: 'desertgrass',
    surfaceMin: estimated(20, '°C', ''),
    surfaceMax: estimated(55, '°C', ''),
    airMin: estimated(18, '°C', ''),
    airMax: estimated(36, '°C', ''),
    sunrise: measured(5.6, 'h', [], 'Summer at 32° N.'),
    sunset: measured(19.5, 'h', [], ''),
    soilDiffusivity: estimated(0.55, 'mm²/s', 'Dry sandy loam.'),
    startHour: 5.2,
    indoor: false,
  },
  arena: {
    width: estimated(10000, 'mm', 'Foragers travel up to ~20 m; arena 10 m.', 'gordon2016'),
    height: estimated(10000, 'mm', ''),
    cell: estimated(10, 'mm', ''),
    relief: estimated(40, 'mm', ''),
  },
  morphology: {
    lengthMin: estimated(5.5, 'mm', ''),
    lengthMax: estimated(7.5, 'mm', ''),
    sizeDistribution: 'continuous',
    massCoef: estimated(0.018, 'mg/mm³', ''),
    headAllometry: estimated(0.1, '', ''),
    legRatio: estimated(0.95, '', ''),
    rideHeight: estimated(0.25, '', ''),
    petioleNodes: 2,
    cocoons: false,
    antennalClub: false,
    spines: false,
    colors: { head: '#7d2412', mesosoma: '#8c2c15', gaster: '#6d2312', legs: '#953a1f' },
  },
  locomotion: {
    v28: measured(18.1, 'mm/s', 'hurlbert2008', 'P. barbatus (Morehead & Feener 1998 data) at 28 °C.'),
    refMass: estimated(4.5, 'mg', ''),
    activationEnergy: measured(0.33, 'eV', 'hurlbert2008'),
    massExponent: measured(0.25, '', 'hurlbert2008'),
    tempMin: estimated(12, '°C', ''),
    tempOpt: estimated(45, '°C', 'Measured to 52.4 °C.', 'hurlbert2008'),
    tempMax: estimated(51, '°C', ''),
    turnNoise: estimated(1.0, 'rad/√s', ''),
    loadSlope: derived(0.12, '1/body-mass', 'burd1996', ''),
  },
  senses: {
    antennaRatio: estimated(0.5, '', ''),
    antennaAngle: estimated(0.55, 'rad', ''),
    trailGain: estimated(3, 'rad/s', 'Weak trunk-trail orientation.'),
    foodDetect: estimated(20, 'mm', 'Seeds found at close range.'),
    nestDetect: estimated(80, 'mm', ''),
  },
  navigation: {
    compassBias: estimated(0.07, 'rad', ''),
    compassNoise: estimated(0.02, 'rad', ''),
    odometerError: estimated(0.1, '', ''),
    visualCatchment: estimated(400, 'mm', ''),
    systematicSearch: false,
    siteFidelity: estimated(0.7, '', 'Foragers return to the same foraging area.', 'gordon2016'),
    memoryFailures: estimated(3, 'visits', ''),
  },
  foraging: {
    mode: 'harvester',
    foods: ['seed', 'insect'],
    bodyTempMin: estimated(20, '°C', ''),
    bodyTempMax: estimated(45, '°C', 'Foraging stops in the midday heat.'),
    diurnal: true,
    cropVolume: estimated(0.3, 'µL', ''),
    drinkRate: estimated(0.004, 'µL/s', ''),
    carryCapacity: estimated(6, '× body mass', ''),
    giveUpTime: estimated(1800, 's', ''),
    exploreRadius: estimated(3000, 'mm', ''),
    restTime: estimated(60, 's', 'Foragers wait near the entrance between trips.'),
    scoutRate: estimated(0, '/h', 'Exits governed by the interaction model instead.'),
    extranidalHazard: estimated(1 / (60 * 3600), '1/s', ''),
    recruitProbability: estimated(0, '', 'No recruitment trails to seeds.'),
    recruitContacts: estimated(0, 'ants', ''),
    recruitResponse: estimated(0, '', ''),
  },
  pheromones: [
    {
      id: 'trail',
      label: 'Trunk-trail orientation',
      gland: 'Dufour gland',
      lifetime: estimated(86400, 's', 'Trunk trails persist for days.'),
      deposit: estimated(0.05, 'units/mm', 'Weak; laid by returning foragers.'),
      threshold: estimated(1, 'units/mm', ''),
      weight: estimated(0.5, '', ''),
      laidBy: 'all-foragers',
    },
  ],
  alarm: {
    radius: derived(60, 'mm', 'bossert1963', 'Measured for P. badius.'),
    fade: derived(35, 's', 'bossert1963', 'Measured for P. badius.'),
    aggression: estimated(0.6, '', 'Painful sting.'),
  },
  colony: {
    queens: measured(1, '', 'holldobler1990'),
    workers: estimated(2000, 'workers', 'Scaled; mature colonies ~10 000–12 000.', 'gordon2016'),
    eggs: estimated(100, '', ''),
    larvae: estimated(120, '', ''),
    pupae: estimated(80, '', ''),
    eggsPerQueenDay: estimated(50, 'eggs/day', ''),
    workerLifespan: estimated(365, 'days', 'Workers live ~1 year.'),
    forageAge: estimated(45, 'days', ''),
    inactiveFraction: estimated(0.4, '', ''),
    volumePerWorker: estimated(150, 'mm³', 'Includes granaries.', 'tschinkel2004'),
    workerCap: 5000,
  },
  development: {
    egg: estimated(10, 'd', ''),
    larva: estimated(14, 'd', ''),
    pupa: estimated(14, 'd', ''),
    refTemp: estimated(30, '°C', ''),
    lowerThreshold: estimated(15, '°C', ''),
    upperThreshold: estimated(36, '°C', ''),
    broodTempPref: estimated(30, '°C', ''),
  },
  nest: {
    architecture: 'harvester',
    voxel: estimated(5, 'mm', ''),
    depth: estimated(900, 'mm', 'Pogonomyrmex nests reach 2 m; scaled.', 'tschinkel2004'),
    radius: estimated(220, 'mm', ''),
    tunnelWidth: derived(12, 'mm', 'tschinkel2004', 'Measured on P. badius (shaft diameter ~1–2 cm, helix 4–6 cm); transferred to P. barbatus.', { sourceSpecies: 'Pogonomyrmex badius' }),
    chamberHeight: estimated(15, 'mm', ''),
    moundHeight: estimated(30, 'mm', 'Low gravel mound.'),
    moundRadius: estimated(200, 'mm', 'Low gravel mound over the entrance.'),
    pelletTime: estimated(60, 's', ''),
    pelletVolume: estimated(4, 'mm³', ''),
    queenDepth: estimated(0.8, '', ''),
  },
  physiology: {
    metabolicRate: derived(1.2, 'µg/h/mg^0.75', 'gillooly2001', ''),
    activeFactor: estimated(3, '×', ''),
    reserveDays: estimated(20, 'd', ''),
    larvalProtein: estimated(0.6, 'mg/mg', ''),
    eggCost: estimated(0.05, 'mg', ''),
  },
  special: {
    harvester: {
      c: derived(0.06, '(ants/s)⁻¹ per return', 'prabhakar2012', 'Fitted c ranged 0.01–0.25; mid-low value.'),
      q: measured(0.05, '(ants/s)⁻¹ per departure', 'prabhakar2012'),
      d: measured(0, 'ants/s', 'prabhakar2012'),
      alphaMin: measured(0.01, 'ants/s', 'prabhakar2012'),
      patrollers: estimated(30, 'ants', 'Scaled patroller force.', 'greene2007'),
      patrolDuration: estimated(900, 's', ''),
      seedsPerDay: estimated(1500, 'seeds/day', 'Seed rain across the arena.'),
    },
  },
  world: { aphidColonies: 0, sugarDrops: 0, insects: 4, insectRainPerHour: 2, seeds: 800, plants: 10, stones: 8, grit: 0, clearedDisc: 900 },
};
