import { derived, estimated, measured } from '../core/param';
import type { SpeciesDef } from './types';

export const solenopsis: SpeciesDef = {
  id: 'solenopsis',
  name: 'Solenopsis invicta',
  common: 'Red imported fire ant',
  subfamily: 'Myrmicinae',
  blurb:
    'An aggressive, invasive omnivore with continuous worker polymorphism that becomes bimodal (minors and majors) as colonies grow. Recruitment uses a fast-fading Dufour-gland trail, so trails exist only while food keeps being found. Brood is shuttled up and down the mound to track temperature.',
  highlights: [
    'Dufour gland trail pheromone fades in ~100 s (Wilson 1962)',
    'Size polymorphism: incipient colonies monomorphic, majors appear as colonies grow (Tschinkel)',
    'Cooperative transport of large prey; intense alarm/attack response',
    'Daily thermoregulatory brood transport along the depth gradient (Penick & Tschinkel 2008)',
    'Soil mound with deep shafts',
  ],
  habitat: {
    label: 'Subtropical pasture, summer (SE USA)',
    ground: 'pasture',
    surfaceMin: estimated(23, '°C', 'Humid subtropical summer night.'),
    surfaceMax: estimated(46, '°C', 'Sunny bare soil in Florida summer.'),
    airMin: estimated(23, '°C', ''),
    airMax: estimated(33, '°C', ''),
    sunrise: measured(6.5, 'h', [], 'Sunrise at 30° N in summer.'),
    sunset: measured(20.3, 'h', [], ''),
    soilDiffusivity: estimated(0.5, 'mm²/s', 'Sandy soil.'),
    startHour: 7,
    indoor: false,
  },
  arena: {
    width: estimated(1500, 'mm', ''),
    height: estimated(1100, 'mm', ''),
    cell: estimated(2, 'mm', ''),
    relief: estimated(20, 'mm', ''),
  },
  morphology: {
    lengthMin: measured(2.4, 'mm', 'tschinkel2006'),
    lengthMax: measured(6.0, 'mm', 'tschinkel2006'),
    sizeDistribution: 'fire',
    massCoef: estimated(0.011, 'mg/mm³', ''),
    headAllometry: estimated(0.25, '', 'Majors have disproportionately large heads.'),
    legRatio: estimated(0.8, '', ''),
    rideHeight: estimated(0.2, '', ''),
    petioleNodes: 2,
    cocoons: false,
    antennalClub: true,
    spines: false,
    colors: { head: '#8c3c1c', mesosoma: '#9a4520', gaster: '#3a1b0e', legs: '#a0532a' },
  },
  locomotion: {
    v28: measured(16.7, 'mm/s', 'hurlbert2008', 'Speed at 28 °C (Rigatuso et al. 2000 data).'),
    refMass: estimated(0.5, 'mg', 'Typical minor/media worker.'),
    activationEnergy: measured(0.53, 'eV', 'hurlbert2008'),
    massExponent: measured(0.25, '', 'hurlbert2008'),
    tempMin: estimated(10, '°C', 'Hurlbert data cover 9.5–32.8 °C.'),
    tempOpt: estimated(36, '°C', ''),
    tempMax: estimated(46, '°C', ''),
    turnNoise: estimated(1.2, 'rad/√s', ''),
    loadSlope: derived(0.12, '1/body-mass', 'burd1996', ''),
  },
  senses: {
    antennaRatio: estimated(0.5, '', ''),
    antennaAngle: estimated(0.6, 'rad', ''),
    trailGain: estimated(7, 'rad/s', ''),
    foodDetect: estimated(15, 'mm', ''),
    nestDetect: estimated(25, 'mm', ''),
  },
  navigation: {
    compassBias: estimated(0.15, 'rad', ''),
    compassNoise: estimated(0.04, 'rad', ''),
    odometerError: estimated(0.15, '', ''),
    visualCatchment: estimated(50, 'mm', ''),
    systematicSearch: false,
    siteFidelity: estimated(0.4, '', ''),
    memoryFailures: estimated(1, 'visits', ''),
  },
  foraging: {
    mode: 'mass',
    foods: ['sugar', 'honeydew', 'insect', 'seed'],
    bodyTempMin: estimated(19, '°C', 'Foraging occurs at soil temperatures ~19–36 °C (Porter & Tschinkel).', 'tschinkel2006'),
    bodyTempMax: estimated(38, '°C', '', 'tschinkel2006'),
    diurnal: false,
    cropVolume: estimated(0.06, 'µL', ''),
    drinkRate: estimated(0.0015, 'µL/s', ''),
    carryCapacity: estimated(5, '× body mass', ''),
    giveUpTime: estimated(900, 's', ''),
    exploreRadius: estimated(300, 'mm', ''),
    restTime: estimated(200, 's', ''),
    scoutRate: estimated(0.6, '/h', ''),
    extranidalHazard: estimated(1 / (40 * 3600), '1/s', ''),
    recruitProbability: estimated(0.9, '', ''),
    recruitContacts: estimated(6, 'ants', 'Fire ants recruit large numbers quickly.'),
    recruitResponse: estimated(0.4, '', ''),
  },
  pheromones: [
    {
      id: 'trail',
      label: 'Recruitment trail',
      gland: 'Dufour gland',
      lifetime: derived(110, 's', 'wilson1962', 'Active 85–125 s on glass at 28 °C; lifetime ≈ midpoint.'),
      deposit: estimated(2.5, 'units/mm', 'High deposition needed for the trail to reach the nest before it fades.'),
      threshold: estimated(0.6, 'units/mm', ''),
      weight: estimated(1, '', ''),
      laidBy: 'recruiters',
    },
  ],
  alarm: {
    radius: estimated(50, 'mm', 'Poison gland pyrazine alarm.', 'bossert1963'),
    fade: estimated(30, 's', '', 'bossert1963'),
    aggression: estimated(0.95, '', 'Highly aggressive; mass stinging.'),
  },
  colony: {
    queens: measured(1, '', 'tschinkel2006', 'Monogyne form.'),
    workers: estimated(1500, 'workers', 'Young colony (mature colonies 200 000+).'),
    eggs: estimated(200, '', ''),
    larvae: estimated(200, '', ''),
    pupae: estimated(150, '', ''),
    eggsPerQueenDay: estimated(150, 'eggs/day', 'Mature queens can lay >1000/day; limited by colony size here.', 'tschinkel2006'),
    workerLifespan: estimated(70, 'days', 'Minor workers ~30–90 d at summer temperatures; majors longer (scaled by size).', 'porter1988'),
    forageAge: estimated(30, 'days', ''),
    inactiveFraction: estimated(0.4, '', ''),
    volumePerWorker: estimated(25, 'mm³', ''),
    workerCap: 5000,
  },
  development: {
    egg: derived(7, 'd', 'porter1988', 'Egg-to-adult ~25 d at ~30 °C.'),
    larva: derived(8, 'd', 'porter1988', ''),
    pupa: derived(10, 'd', 'porter1988', ''),
    refTemp: measured(30, '°C', 'porter1988'),
    lowerThreshold: derived(21, '°C', 'porter1988', 'Brood production ceases below ~21–24 °C.'),
    upperThreshold: estimated(35, '°C', ''),
    broodTempPref: derived(31, '°C', 'penick2008', 'Brood moved to warm upper mound layers.'),
  },
  nest: {
    architecture: 'fireant',
    voxel: estimated(3, 'mm', ''),
    depth: estimated(600, 'mm', 'Shafts reach ~1 m in mature nests; scaled.', 'tschinkel2006'),
    radius: estimated(180, 'mm', ''),
    tunnelWidth: estimated(6, 'mm', ''),
    chamberHeight: estimated(9, 'mm', ''),
    moundHeight: estimated(90, 'mm', 'Young colony mound.'),
    moundRadius: estimated(140, 'mm', ''),
    pelletTime: estimated(45, 's', ''),
    pelletVolume: estimated(1.2, 'mm³', ''),
    queenDepth: estimated(0.45, '', ''),
  },
  physiology: {
    metabolicRate: derived(1.2, 'µg/h/mg^0.75', 'gillooly2001', ''),
    activeFactor: estimated(3, '×', ''),
    reserveDays: estimated(10, 'd', ''),
    larvalProtein: estimated(0.6, 'mg/mg', ''),
    eggCost: estimated(0.006, 'mg', ''),
  },
  special: {},
  world: { aphidColonies: 1, sugarDrops: 1, insects: 4, insectRainPerHour: 4, seeds: 40, plants: 2, stones: 4, grit: 0 },
};
