import { derived, estimated, measured } from '../core/param';
import type { SpeciesDef } from './types';

export const temnothorax: SpeciesDef = {
  id: 'temnothorax',
  name: 'Temnothorax albipennis',
  common: 'Rock ant',
  subfamily: 'Myrmicinae',
  blurb:
    'A tiny ant living in small colonies inside thin rock crevices. Instead of mass trails, a knowledgeable forager teaches one nestmate the route by tandem running, slowing down and waiting whenever its follower falls behind. Workers build a perimeter wall of grains whose size tracks colony size.',
  highlights: [
    'Tandem running: one-to-one teaching with bidirectional gap feedback (Franks & Richardson 2006)',
    'Leaders travel ~4× slower than alone',
    'Nests in pre-formed flat rock crevices; builds a grain wall sized to the colony (Franks & Deneubourg 1997)',
    'Small colonies (≈100–200 workers), single queen',
    'Slow, tiny workers; no mass recruitment pheromone',
  ],
  habitat: {
    label: 'Coastal rocky heath (S. England), summer',
    ground: 'heath',
    surfaceMin: estimated(12, '°C', ''),
    surfaceMax: estimated(32, '°C', ''),
    airMin: estimated(12, '°C', ''),
    airMax: estimated(22, '°C', ''),
    sunrise: measured(5.0, 'h', [], 'Summer at 50° N.'),
    sunset: measured(21.2, 'h', [], ''),
    soilDiffusivity: estimated(1.2, 'mm²/s', 'Rock (granite ~1.2 mm²/s).'),
    startHour: 10,
    indoor: false,
  },
  arena: {
    width: estimated(400, 'mm', ''),
    height: estimated(300, 'mm', ''),
    cell: estimated(0.6, 'mm', ''),
    relief: estimated(4, 'mm', ''),
  },
  morphology: {
    lengthMin: measured(2.3, 'mm', 'holldobler1990'),
    lengthMax: measured(2.9, 'mm', 'holldobler1990'),
    sizeDistribution: 'mono',
    massCoef: estimated(0.01, 'mg/mm³', ''),
    headAllometry: estimated(0, '', ''),
    legRatio: estimated(0.75, '', ''),
    rideHeight: estimated(0.2, '', ''),
    petioleNodes: 2,
    cocoons: false,
    antennalClub: true,
    spines: true,
    colors: { head: '#a06c2c', mesosoma: '#ad7834', gaster: '#4d3017', legs: '#b78545' },
  },
  locomotion: {
    v28: estimated(5, 'mm/s', 'Small, slow myrmicine.'),
    refMass: estimated(0.17, 'mg', ''),
    activationEnergy: derived(0.47, 'eV', 'hurlbert2008', 'Mean across species.'),
    massExponent: measured(0.25, '', 'hurlbert2008'),
    tempMin: estimated(6, '°C', ''),
    tempOpt: estimated(30, '°C', ''),
    tempMax: estimated(42, '°C', ''),
    turnNoise: estimated(1.4, 'rad/√s', ''),
    loadSlope: derived(0.12, '1/body-mass', 'burd1996', ''),
  },
  senses: {
    antennaRatio: estimated(0.5, '', ''),
    antennaAngle: estimated(0.6, 'rad', ''),
    trailGain: estimated(0, 'rad/s', 'No trail following.'),
    foodDetect: estimated(6, 'mm', ''),
    nestDetect: estimated(10, 'mm', ''),
  },
  navigation: {
    compassBias: estimated(0.12, 'rad', ''),
    compassNoise: estimated(0.04, 'rad', ''),
    odometerError: estimated(0.15, '', ''),
    visualCatchment: estimated(25, 'mm', 'Landmarks learned during tandem runs.', 'franks2006'),
    systematicSearch: false,
    siteFidelity: estimated(0.9, '', ''),
    memoryFailures: estimated(2, 'visits', ''),
  },
  foraging: {
    mode: 'tandem',
    foods: ['sugar', 'insect'],
    bodyTempMin: estimated(12, '°C', ''),
    bodyTempMax: estimated(36, '°C', ''),
    diurnal: false,
    cropVolume: estimated(0.02, 'µL', ''),
    drinkRate: estimated(0.0004, 'µL/s', ''),
    carryCapacity: estimated(4, '× body mass', ''),
    giveUpTime: estimated(1500, 's', ''),
    exploreRadius: estimated(80, 'mm', ''),
    restTime: estimated(600, 's', ''),
    scoutRate: estimated(0.4, '/h', ''),
    extranidalHazard: estimated(1 / (80 * 3600), '1/s', ''),
    recruitProbability: estimated(0.6, '', 'Successful foragers often initiate a tandem run.'),
    recruitContacts: estimated(1, 'ants', 'One follower per tandem run.'),
    recruitResponse: estimated(1, '', ''),
  },
  pheromones: [],
  alarm: {
    radius: estimated(10, 'mm', ''),
    fade: estimated(10, 's', ''),
    aggression: estimated(0.1, '', 'Timid.'),
  },
  colony: {
    queens: measured(1, '', 'franks1997'),
    workers: estimated(150, 'workers', 'Colonies of ~50–500 workers.', 'franks1997'),
    eggs: estimated(25, '', ''),
    larvae: estimated(40, '', ''),
    pupae: estimated(15, '', ''),
    eggsPerQueenDay: estimated(3, 'eggs/day', ''),
    workerLifespan: estimated(400, 'days', 'Small-colony ants are long-lived.'),
    forageAge: estimated(40, 'days', ''),
    inactiveFraction: estimated(0.5, '', 'Many Temnothorax workers are inactive.'),
    volumePerWorker: estimated(6, 'mm³', ''),
    workerCap: 1500,
  },
  development: {
    egg: estimated(12, 'd', ''),
    larva: estimated(24, 'd', ''),
    pupa: estimated(14, 'd', ''),
    refTemp: estimated(25, '°C', ''),
    lowerThreshold: estimated(12, '°C', ''),
    upperThreshold: estimated(32, '°C', ''),
    broodTempPref: estimated(25, '°C', ''),
  },
  nest: {
    architecture: 'crevice',
    voxel: estimated(0.6, 'mm', ''),
    depth: estimated(2, 'mm', 'Crevice height.'),
    radius: estimated(30, 'mm', 'Half-width of the crevice.'),
    tunnelWidth: estimated(2, 'mm', ''),
    chamberHeight: estimated(1.8, 'mm', 'Thin crevice ≈1.6–2 mm.'),
    moundHeight: estimated(0, 'mm', ''),
    moundRadius: estimated(0, 'mm', ''),
    pelletTime: estimated(0, 's', 'No excavation.'),
    pelletVolume: estimated(0.05, 'mm³', ''),
    queenDepth: estimated(0.5, '', ''),
  },
  physiology: {
    metabolicRate: derived(1.2, 'µg/h/mg^0.75', 'gillooly2001', ''),
    activeFactor: estimated(3, '×', ''),
    reserveDays: estimated(20, 'd', ''),
    larvalProtein: estimated(0.6, 'mg/mg', ''),
    eggCost: estimated(0.003, 'mg', ''),
  },
  special: {
    tandem: {
      gapStop: estimated(2.5, 'mm', 'Leader stops when follower contact is lost beyond ~1 body length.', 'franks2006'),
      gapResume: estimated(0.8, 'mm', 'Leader resumes after the follower taps its hind legs.', 'franks2006'),
      followerPause: estimated(0.15, '1/s', 'Followers pause to look around and learn landmarks.', 'franks2006'),
      leaderSlowdown: derived(0.6, '', 'franks2006', 'Leader speed while leading; with waiting this yields ~4× slower progress.'),
    },
    crevice: {
      cavityHeight: estimated(1.8, 'mm', ''),
      wallAreaPerWorker: estimated(4, 'mm²', 'Floor area inside the wall per worker.', 'franks1997'),
      grainVolume: estimated(0.03, 'mm³', 'Sand grains ~0.3–0.5 mm.'),
    },
  },
  world: { aphidColonies: 0, sugarDrops: 1, insects: 2, insectRainPerHour: 0.5, seeds: 0, plants: 2, stones: 6, grit: 300 },
};
